name: Repo Sync

on: [push]
jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: ${{ secrets.SOURCE_REPO }} #URL primer repositorio https://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@github.com/gh-test-sync/develop.git
        source_branch: main
        destination_branch: ${{ secrets.INTERMEDIATE_BRANCH }} #Repositorio destino.
        github_token: ${{ secrets.GH_PAT }} #Clave primer repositorio.
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        destination_branch: main
        github_token: ${{ secrets.GT_STG_TOKEN }}