
name: "git repo sync"
on:
  push:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v3
      with:
        source_repo_url: git@github.com:gh-test-sync/develop.git
        source_branch: main
        dest_repo_url: git@github.com:gh-test-sync/staging.git
        dest_branch: main
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}