# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://johnjaider1000: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@github.com/gh-test-sync/develop.git" #URL primer repositorio https://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@github.com/gh-test-sync/develop.git
          source_branch: "main"
          destination_repo: https://johnjaider1000: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@github.com/gh-test-sync/staging.git #Repositorio destino.
          destination_branch: "main"